objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <description>Name of the Agency</description>
        <label>Agency Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>INTERPOL_Cases__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>INTERPOL Case</label>
        <referenceTo>ComplaintCase</referenceTo>
        <relationshipLabel>Related Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/ComplaintCase.object
<CustomObject>
    <fields>
        <fullName>Interpol_Cases__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interpol Cases</relationshipLabel>
        <relationshipName>Interpol_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/doj_SubjectRelatedViewControllerTest.cls
@isTest
public class doj_SubjectRelatedViewControllerTest {

    @isTest
    static void testFetchSubjectIdValidRecord() {
        // Create test data
        Contact testSubject = new Contact(FirstName = 'John', LastName = 'Doe');
        insert testSubject;

        Account testAcc = new Account(Name = 'testacc', Agency_Name__c = 'testAccountAgency');
        insert testAcc;

        Case testInq = new Case(Description = 'test', AccountId = testAcc.Id);
        insert testInq;

        PublicComplaint testpublicComplaint = new PublicComplaint(AccountId = testAcc.Id, IncidentDate = Date.newInstance(2025, 1, 10));
        insert testpublicComplaint;

        ComplaintCase testCase = new ComplaintCase(
            Interpol_Cases__c = testSubject.Id,
            PublicComplaintId = testpublicComplaint.Id,
            CaseId = testInq.Id
        );
        insert testCase;

        Test.startTest();
        // Call the method with a valid ComplaintCase ID
        String subjectId = doj_SubjectRelatedViewController.fetchSubjectId(testCase.Id);
        Test.stopTest();

        // Assert the result
        System.assertEquals(testCase.Interpol_Cases__c, subjectId, 'The subject ID should match the Interpol_Cases__c field value.');
    }

    @isTest
    static void testFetchSubjectIdInvalidRecordId() {
        Test.startTest();
        try {
            // Call the method with a null ID
            doj_SubjectRelatedViewController.fetchSubjectId(null);
            System.assert(false, 'An exception should have been thrown for a null record ID.');
        } catch (QueryException e) {
            System.assert(true, 'QueryException correctly thrown for invalid record ID.');
        }
        Test.stopTest();
    }

    @isTest
    static void testFetchSubjectIdNoInterpolCases() {
        Contact testSubject = new Contact(FirstName = 'John', LastName = 'Doe');
        insert testSubject;

        Account testAcc = new Account(Name = 'testacc', Agency_Name__c = 'testAccountAgency');
        insert testAcc;

        Case testInq = new Case(Description = 'test', AccountId = testAcc.Id);
        insert testInq;

        PublicComplaint testpublicComplaint = new PublicComplaint(AccountId = testAcc.Id, IncidentDate = Date.newInstance(2025, 1, 10));
        insert testpublicComplaint;

        ComplaintCase testCase = new ComplaintCase(
            Interpol_Cases__c = null,
            PublicComplaintId = testpublicComplaint.Id,
            CaseId = testInq.Id
        );
        insert testCase;

        Test.startTest();
        // Call the method with a ComplaintCase ID that has no Interpol_Cases__c value
        String subjectId = doj_SubjectRelatedViewController.fetchSubjectId(testCase.Id);
        Test.stopTest();

        // Assert that the result is null
        System.assertEquals(null, subjectId, 'The subject ID should be null when Interpol_Cases__c is not populated.');
    }
}