objects/Alias__c.object
<CustomObject>
    <fields>
        <fullName>Aliases__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aliases</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Aliases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Alias</label>
    <nameField>
        <label>Aliases Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Businesses__c.object
<CustomObject>
    <fields>
        <fullName>Businesses__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Businesses</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Businesses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Aliases__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aliases</label>
        <referenceTo>Alias__c</referenceTo>
        <relationshipLabel>Related Aliases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Businesses__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Businesses</label>
        <referenceTo>Businesses__c</referenceTo>
        <relationshipLabel>Related Businesses</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Control_Nr__c</fullName>
        <label>Control_Nr</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DOBs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOBs</label>
        <referenceTo>DOB__c</referenceTo>
        <relationshipLabel>Related DOBs</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ENTITY_ID__c</fullName>
        <label>ENTITY_ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FileNumber__c</fullName>
        <label>FileNumber</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>INTERPOL_Cases__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>INTERPOL Case</label>
        <referenceTo>ComplaintCase</referenceTo>
        <relationshipLabel>Related Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offenses__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offenses</label>
        <referenceTo>Offence__c</referenceTo>
        <relationshipLabel>Related Offenses</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Properties__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Properties</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Related Properties</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status_Id__c</fullName>
        <label>Status Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type_Of_Notification__c</fullName>
        <label>Type Of Notification</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/ComplaintCase.object
<CustomObject>
    <fields>
        <fullName>Aliases__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aliases</label>
        <referenceTo>Alias__c</referenceTo>
        <relationshipLabel>Related Aliases</relationshipLabel>
        <relationshipName>Complaint_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Businesses__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Businesses</label>
        <referenceTo>Businesses__c</referenceTo>
        <relationshipLabel>Related Businesses</relationshipLabel>
        <relationshipName>Complaint_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Control_Nr__c</fullName>
        <label>Control_Nr</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DOBs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOB</label>
        <referenceTo>DOB__c</referenceTo>
        <relationshipLabel>Related DOBs</relationshipLabel>
        <relationshipName>Complaint_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ENTITY_ID__c</fullName>
        <label>ENTITY_ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FileNumber__c</fullName>
        <label>FileNumber</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Interpol_Cases__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subject</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interpol Cases</relationshipLabel>
        <relationshipName>Interpol_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offenses__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offenses</label>
        <referenceTo>Offence__c</referenceTo>
        <relationshipLabel>RelatedOffenses</relationshipLabel>
        <relationshipName>Complaint_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Properties__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Properties</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Related Properties</relationshipLabel>
        <relationshipName>Complaint_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <label>Reference</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Saved_Search_Results__c</fullName>
        <label>Saved Search Results</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Id__c</fullName>
        <label>Status Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type_Of_Notification__c</fullName>
        <label>Type Of Notification</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Aliases__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aliases</label>
        <referenceTo>Alias__c</referenceTo>
        <relationshipLabel>Related Aliases</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Businesses__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Businesses</label>
        <referenceTo>Businesses__c</referenceTo>
        <relationshipLabel>Related Businesses</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOBs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOBs</label>
        <referenceTo>DOB__c</referenceTo>
        <relationshipLabel>Related DOBs</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offenses__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offenses</label>
        <referenceTo>Offence__c</referenceTo>
        <relationshipLabel>Related Offenses</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Properties__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Related Properties</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/DOB__c.object
<CustomObject>
    <fields>
        <fullName>DOBs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOBs</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>DOBs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DOB</label>
    <nameField>
        <label>DOB</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DOBs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Inquiry_Interpol_Case_Junction__c.object
<CustomObject>
    <description>Inquiry INTERPOL Case Junction to enable Many to many Relationship</description>
    <label>Association for Inquiry to INTERPOL Case</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>Inquiry INTERPOL Relation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inquiries and INTERPOL Cases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Offence__c.object
<CustomObject>
    <fields>
        <fullName>Offenses__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offenses</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Offenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Offence</label>
    <nameField>
        <label>Offence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/updateCaseController.cls
/**
  Author: Chandra
  Description: Utility Apex class for LWC 
  Created date : 09/10/2024
 */

public with sharing class updateCaseController {
    @AuraEnabled(cacheable=true)
    public static list<ComplaintCase>  getCases(){ 
        return [SELECT Id,Name, CaseId,case.casenumber, Saved_Search_Results__c,PublicComplaintId,PublicComplaint.Name, Offenses__c, Offenses__r.Name, Aliases__c, DOBs__c, Businesses__c, Properties__c, Interpol_Cases__c, Reference__c, Office__c, Type_Of_Notification__c, Control_Nr__c, ENTITY_ID__c, Status_Id__c, FileNumber__c FROM ComplaintCase];
    }

    @AuraEnabled(cacheable=true)
    public static list<Alias__c>  getAlias(){ 
        return [SELECT Id, Aliases__c,Aliases__r.Name,Name, OwnerId, owner.name FROM Alias__c] ;
    }

    @AuraEnabled(cacheable=true)
    public static list<DOB__c>  getDob(){ 
        return [SELECT Id, Name, DOBs__c,DOBs__r.name, OwnerId, owner.name FROM DOB__c] ;
    }
    //Added method to retrieve business reocrd info for lwc Que.C 09/30/24
    @AuraEnabled(cacheable=true)
    public static list<Businesses__c>  getBus(){ 
        return [SELECT Id, Name, Street_Address__c, Businesses__c, Businesses__r.name, OwnerId, owner.name FROM Businesses__c] ;
    }
    
    
        //Added method to retrieve business reocrd info for lwc Que.C 09/30/24
    @AuraEnabled(cacheable=true)
    public static list<Inquiry_Interpol_Case_Junction__c>  getassciation(id recordid, string pagetype){ 
        if(pagetype == 'full'){
            system.debug('In full');
        return [SELECT Id, Inquiry__c,Inquiry__r.CaseNumber, Interpol_Case__c,Interpol_Case__r.Name, CreatedDate, CreatedById, CreatedBy.Name,LastModifiedBy.Name, LastModifiedDate, LastModifiedById  FROM Inquiry_Interpol_Case_Junction__c where Interpol_Case__c  =: recordid or Inquiry__c =: recordid limit 2000] ;
        }else{
              system.debug('In related');
             return [SELECT Id, Inquiry__c,Inquiry__r.CaseNumber, Interpol_Case__c,Interpol_Case__r.Name, CreatedDate, CreatedById, CreatedBy.Name,LastModifiedBy.Name, LastModifiedDate, LastModifiedById  FROM Inquiry_Interpol_Case_Junction__c where Interpol_Case__c  =: recordid or Inquiry__c =: recordid limit 10] ;
       
        }
    }
    
    
    @AuraEnabled(cacheable=true)
    public static integer getassciationcount(id recordid){ 
        integer recount = [SELECT count() FROM Inquiry_Interpol_Case_Junction__c where Interpol_Case__c  =: recordid or Inquiry__c =: recordid];
        return  recount;
    }
    
    /*
        @AuraEnabled(cacheable=true)
    public static boolean emptycall(id recordid){ 
       
        return  true;
    }
    */
            //Added method to retrieve business reocrd info for lwc Que.C 09/30/24
    @AuraEnabled
    public static list<ComplaintCase>  searchRecords(String searchKey){ 
        if (String.isEmpty(searchKey)) {
            return new List<ComplaintCase>();
        }
        
         String query = '%' + searchKey + '%';
           return [
            SELECT Id, Name
            FROM ComplaintCase
            WHERE Name LIKE :query
            LIMIT 10
        ]; 
        
     //   return [SELECT Id, Inquiry__c,Inquiry__r.CaseNumber, Interpol_Case__c,Interpol_Case__r.Name FROM Inquiry_Interpol_Case_Junction__c where Interpol_Case__c  =: recordid] ;
    }
    
    
    
}