objects/Case.object
<CustomObject>
    <fields>
        <fullName>CC__c</fullName>
        <label>CC</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Owning_Division__c</fullName>
        <label>Owning Division</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Received_On__c</fullName>
        <label>Received On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sender__c</fullName>
        <label>Sender</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type_Of_Notification__c</fullName>
        <label>Type Of Notification</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Identification Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>TextArea</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/caseInqueryController.cls
/*Developed By: Henry Dennis | Date: 9/5/2024
  Description: controller class File for the Interpol Case Inquiry LWC component
*/

public with sharing class caseInqueryController {
    
    /*This is the Inquiry query.*/
    @AuraEnabled
    public static List<Case> getCaseInquiries(){
        return[SELECT CaseNumber, Type, Subject, Status, 
        Priority, Type_Of_Notification__c, Sender__c, To__c, CC__c, Received_On__c, 
        Owning_Division__c FROM Case];
    }

     /*This is the Search Inquiry query.*/
    @AuraEnabled
    public static List<Case> searchInquiry(String searchString){
        List<List<SObject>> inquiries = [FIND :searchString IN ALL FIELDS RETURNING Case(Id, CaseNumber, Type, Subject, Status,
        Priority, Type_Of_Notification__c, Sender__c, To__c, CC__c, Received_On__c, Owning_Division__c)];
        return (List<Case>) inquiries[0];
    }

    /*This is the Property query.*/
    @AuraEnabled
    public static List<Property__c> getProperties(){
       return [SELECT id, Name, owner.name, Category__c, Property_Type__c, Type_of_Document__c, Country__c, Date_of_issue__c, Expiry_Date__c FROM Property__c] ;
    }

}